name: tests

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
      with: # Use deploy key to ensure pushed change trigger checks as well : https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        pip install coverage-badge==1.0.*
      env:
        GH_PAT: ${{ secrets.AUTH_TOKEN }}
    - name: Test with pytest
      timeout-minutes: 5
      run: python -m pytest --cov-report=html:./tests/coverage_report
    - name: Coverage badge update
      run: coverage-badge -o .github/badges/coverage.svg -f
    - name: Read the coverage report
      run: |
        echo 'HTML_COVERAGE_REPORT<<EOF' >> $GITHUB_ENV
        tr -d '\r\n' < ./tests/coverage_report/index.html >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Comment coverage
      uses: actions/github-script@v5
      with:
        script: |
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ env.HTML_COVERAGE_REPORT }}'
          })
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: github.event_name == 'pull_request'   # Only on PR
      with:
        commit_message: 🤖 Update coverage badge & coverage report
